"use client";

import React, { useMemo } from "react";
import { useStore } from "@/lib/store";
import { Invoice, TaskItem } from "@/lib/types";
import { isPastDate } from "@/lib/utils";

/* Shared page header */
export function PageHead({
  title,
  sub,
  actions,
}: {
  title: string;
  sub?: string;
  actions?: React.ReactNode;
}) {
  return (
    <div className="mb-5 flex flex-wrap items-end justify-between gap-3">
      <div>
        <h1 className="text-xl font-extrabold tracking-tight text-ink">
          {title}
        </h1>
        {sub && <p className="mt-0.5 text-sm text-sub">{sub}</p>}
      </div>
      {actions && <div className="flex flex-wrap items-center gap-2">{actions}</div>}
    </div>
  );
}

/* Entity lookup helpers bound to the live DB */
export function useLookups() {
  const { db } = useStore();
  return useMemo(
    () => ({
      user: (id?: string) => db.users.find((u) => u.id === id),
      userName: (id?: string) => db.users.find((u) => u.id === id)?.name ?? "—",
      matter: (id?: string) => db.matters.find((m) => m.id === id),
      matterName: (id?: string) =>
        id ? db.matters.find((m) => m.id === id)?.name ?? "—" : "—",
      client: (id?: string) => db.clients.find((c) => c.id === id),
      clientName: (id?: string) =>
        id ? db.clients.find((c) => c.id === id)?.name ?? "—" : "—",
      lead: (id?: string) => db.leads.find((l) => l.id === id),
      leadName: (id?: string) => {
        const l = db.leads.find((x) => x.id === id);
        return l ? `${l.firstName} ${l.lastName}` : "—";
      },
    }),
    [db]
  );
}

/* Invoice math */
export function invTotal(inv: Invoice): number {
  return inv.items.reduce((s, i) => s + i.amount, 0);
}
export function invPaid(inv: Invoice): number {
  return inv.payments.reduce((s, p) => s + p.amount, 0);
}
export function invBal(inv: Invoice): number {
  return Math.max(invTotal(inv) - invPaid(inv), 0);
}

/* Derived task status (adds "Overdue") */
export function effectiveTaskStatus(t: TaskItem): string {
  if (t.status === "Completed") return "Completed";
  if (isPastDate(t.dueDate)) return "Overdue";
  return t.status;
}

export const TASK_TONE: Record<string, "accent" | "warn" | "ok" | "bad"> = {
  "To Do": "accent",
  "In Progress": "warn",
  Completed: "ok",
  Overdue: "bad",
};

/* Document extension color */
export function extColor(ext: string): string {
  const map: Record<string, string> = {
    pdf: "#d05555",
    docx: "#2f6bff",
    doc: "#2f6bff",
    png: "#7a5af8",
    jpg: "#7a5af8",
    xlsx: "#2f9e77",
    csv: "#2f9e77",
    txt: "#5d6b8c",
  };
  return map[ext.toLowerCase()] ?? "#5d6b8c";
}

export function fmtKb(kb: number): string {
  if (kb >= 1024) return (kb / 1024).toFixed(1) + " MB";
  return Math.round(kb) + " KB";
}

/** Trigger a real browser download of a demo document payload. */
export function downloadDemo(name: string, title: string) {
  const body = [
    "LAWFLOW CRM — DEMO DOCUMENT",
    "============================",
    "",
    title,
    "",
    "This is a simulated document preview generated by the LawFlow CRM demo.",
    "In a production deployment this file would be streamed from encrypted",
    "object storage with an audit-logged, access-controlled download URL.",
    "",
    "Confidential — attorney/client privileged.",
  ].join("\n");
  const blob = new Blob([body], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  a.click();
  URL.revokeObjectURL(url);
}
