import {
  DB, Lead, Contact, Client, Matter, TaskItem, Appointment, DocFile,
  Communication, Note, Activity, Retainer, TimeEntry, Expense, Invoice,
  NotificationItem, AutomationRule, IntakeForm, IntakeSubmission,
  ConflictCheck, AuditLog, User,
} from "./types";
import { addDaysISO, stampDaysAgo, stampDaysAhead } from "./utils";

const users: User[] = [
  { id: "u1", name: "Amira Shah", email: "amira@lawflow.co", role: "super_admin", title: "Managing Partner", color: "#2f6bff", hourlyRate: 450, twoFactorEnabled: true, lastActive: stampDaysAgo(0, 8, 45) },
  { id: "u2", name: "Daniel Reyes", email: "daniel@lawflow.co", role: "attorney", title: "Senior Attorney — Personal Injury", color: "#2f9e77", hourlyRate: 385, twoFactorEnabled: true, lastActive: stampDaysAgo(0, 9, 10) },
  { id: "u3", name: "Grace Okafor", email: "grace@lawflow.co", role: "attorney", title: "Attorney — Family & Immigration", color: "#7a5af8", hourlyRate: 340, twoFactorEnabled: false, lastActive: stampDaysAgo(0, 7, 55) },
  { id: "u9", name: "Victoria Chen", email: "victoria@lawflow.co", role: "attorney", title: "Attorney — Criminal & Business", color: "#c9862b", hourlyRate: 360, twoFactorEnabled: true, lastActive: stampDaysAgo(1, 17, 20) },
  { id: "u4", name: "Marcus Webb", email: "marcus@lawflow.co", role: "paralegal", title: "Senior Paralegal", color: "#0e9bb5", hourlyRate: 150, twoFactorEnabled: false, lastActive: stampDaysAgo(0, 9, 30) },
  { id: "u5", name: "Lena Kowalski", email: "lena@lawflow.co", role: "intake_manager", title: "Intake Manager", color: "#b065d8", hourlyRate: 95, twoFactorEnabled: false, lastActive: stampDaysAgo(0, 8, 15) },
  { id: "u6", name: "Tom Bradley", email: "tom@lawflow.co", role: "receptionist", title: "Front Desk", color: "#5d6b8c", hourlyRate: 45, twoFactorEnabled: false, lastActive: stampDaysAgo(0, 8, 5) },
  { id: "u7", name: "Rachel Donovan", email: "rachel.donovan@mail.com", role: "client", title: "Client", color: "#d05555", hourlyRate: 0, clientId: "c1", twoFactorEnabled: false, lastActive: stampDaysAgo(1, 19, 40) },
  { id: "u8", name: "Hassan Yilmaz", email: "hassan.yilmaz@mail.com", role: "client", title: "Client", color: "#2f9e77", hourlyRate: 0, clientId: "c2", twoFactorEnabled: false, lastActive: stampDaysAgo(2, 11, 5) },
];

const leads: Lead[] = [
  { id: "l1", firstName: "Marcus", lastName: "Delgado", email: "marcus.delgado@mail.com", phone: "(404) 555-0182", practiceArea: "Personal Injury", caseType: "Auto Accident", description: "Rear-ended at a red light on I-285 by a commercial van. Herniated disc at L4-L5, ongoing physical therapy. Other driver's insurer is disputing liability.", source: "Google Ads", assignedAttorneyId: "u2", intakeManagerId: "u5", status: "New Lead", priority: "High", estimatedValue: 85000, createdAt: stampDaysAgo(1, 9, 12), lastContactAt: stampDaysAgo(1, 9, 40), nextFollowUpAt: addDaysISO(0) },
  { id: "l2", firstName: "Priya", lastName: "Nair", email: "priya.nair@mail.com", phone: "(678) 555-0144", practiceArea: "Immigration", caseType: "H-1B Transfer", description: "H-1B transfer from current employer plus H-4 EAD for spouse. Current visa expires in 5 months; employer change already in motion.", source: "Referral", assignedAttorneyId: "u3", intakeManagerId: "u5", status: "New Lead", priority: "Medium", estimatedValue: 6500, createdAt: stampDaysAgo(0, 8, 5), lastContactAt: stampDaysAgo(0, 8, 5), nextFollowUpAt: addDaysISO(1) },
  { id: "l3", firstName: "Sofia", lastName: "Marino", email: "sofia.marino@mail.com", phone: "(770) 555-0119", practiceArea: "Family Law", caseType: "Child Custody", description: "Seeking primary custody of two children (ages 6 and 9). Ex-spouse relocated out of county without notice. Existing temporary order in place.", source: "Website Form", assignedAttorneyId: "u3", intakeManagerId: "u5", status: "Contacted", priority: "High", estimatedValue: 12000, createdAt: stampDaysAgo(3, 14, 20), lastContactAt: stampDaysAgo(1, 11, 5), nextFollowUpAt: addDaysISO(0) },
  { id: "l4", firstName: "Jamal", lastName: "Carter", email: "jamal.carter@mail.com", phone: "(404) 555-0177", practiceArea: "Criminal Defense", caseType: "Drug Possession", description: "First-offense felony possession charge. Questions about search legality during traffic stop. Arraignment scheduled in two weeks.", source: "Avvo", assignedAttorneyId: "u9", intakeManagerId: "u5", status: "Contacted", priority: "High", estimatedValue: 9500, createdAt: stampDaysAgo(4, 16, 45), lastContactAt: stampDaysAgo(2, 10, 30), nextFollowUpAt: addDaysISO(1) },
  { id: "l5", firstName: "Elena", lastName: "Petrova", email: "elena@petrovafoods.com", phone: "(678) 555-0161", practiceArea: "Business Law", caseType: "Breach of Contract", description: "Vendor failed to deliver per supply agreement, causing ~$60k in losses. Contract has arbitration clause. Wants demand letter sent this month.", source: "Referral", assignedAttorneyId: "u9", status: "Qualified", priority: "Medium", estimatedValue: 22000, createdAt: stampDaysAgo(6, 13, 10), lastContactAt: stampDaysAgo(2, 15, 0), nextFollowUpAt: addDaysISO(2) },
  { id: "l6", firstName: "David", lastName: "Osei", email: "david.osei@mail.com", phone: "(470) 555-0139", practiceArea: "Estate Planning", caseType: "Revocable Trust", description: "Blended family, needs revocable living trust plus updated wills and healthcare directives. Owns two properties and a small business.", source: "Website Form", assignedAttorneyId: "u3", status: "Qualified", priority: "Low", estimatedValue: 4800, createdAt: stampDaysAgo(7, 10, 0), lastContactAt: stampDaysAgo(3, 9, 25), nextFollowUpAt: addDaysISO(3) },
  { id: "l7", firstName: "Angela", lastName: "Brooks", email: "angela.brooks@mail.com", phone: "(404) 555-0126", practiceArea: "Personal Injury", caseType: "Slip and Fall", description: "Slipped on unmarked wet floor at a grocery store. Fractured wrist, out of work 6 weeks. Store incident report exists.", source: "Google Ads", assignedAttorneyId: "u2", intakeManagerId: "u5", status: "Consultation Scheduled", priority: "Medium", estimatedValue: 35000, createdAt: stampDaysAgo(5, 11, 50), lastContactAt: stampDaysAgo(1, 14, 15), nextFollowUpAt: addDaysISO(1) },
  { id: "l8", firstName: "Kevin", lastName: "O'Rourke", email: "kevin.orourke@mail.com", phone: "(678) 555-0158", practiceArea: "Criminal Defense", caseType: "DUI", description: "Second DUI within 5 years. Refused breathalyzer; license suspension hearing pending. Needs representation for both administrative and criminal proceedings.", source: "Bar Association", assignedAttorneyId: "u9", status: "Consultation Scheduled", priority: "Urgent", estimatedValue: 12000, createdAt: stampDaysAgo(2, 17, 30), lastContactAt: stampDaysAgo(0, 9, 5), nextFollowUpAt: addDaysISO(0) },
  { id: "l9", firstName: "Mariana", lastName: "Flores", email: "mariana.flores@mail.com", phone: "(770) 555-0147", practiceArea: "Immigration", caseType: "Asylum", description: "Asylum application, entered US 8 months ago. One-year filing deadline approaching. Has supporting affidavits and country-condition evidence.", source: "Referral", assignedAttorneyId: "u3", intakeManagerId: "u5", status: "Consultation Completed", priority: "Urgent", estimatedValue: 9000, createdAt: stampDaysAgo(9, 15, 20), lastContactAt: stampDaysAgo(1, 16, 45), nextFollowUpAt: addDaysISO(0) },
  { id: "l10", firstName: "Robert", lastName: "Lindqvist", email: "robert@lindqvistdev.com", phone: "(404) 555-0193", practiceArea: "Business Law", caseType: "Partnership Dispute", description: "50/50 partner is diverting company opportunities to a side entity. Operating agreement has non-compete language. Seeking buyout or dissolution strategy.", source: "Website Form", assignedAttorneyId: "u9", status: "Retainer Sent", priority: "High", estimatedValue: 45000, createdAt: stampDaysAgo(11, 10, 40), lastContactAt: stampDaysAgo(2, 13, 30), nextFollowUpAt: addDaysISO(1) },
  { id: "l11", firstName: "Tanya", lastName: "Becker", email: "tanya.becker@mail.com", phone: "(470) 555-0112", practiceArea: "Family Law", caseType: "Divorce", description: "Divorce involving business valuation of a dental practice and two rental properties. Signed retainer returned yesterday — ready to onboard.", source: "Referral", assignedAttorneyId: "u3", intakeManagerId: "u5", status: "Retainer Signed", priority: "High", estimatedValue: 25000, createdAt: stampDaysAgo(14, 12, 15), lastContactAt: stampDaysAgo(1, 10, 0), nextFollowUpAt: addDaysISO(0) },
  { id: "l12", firstName: "Rachel", lastName: "Donovan", email: "rachel.donovan@mail.com", phone: "(404) 555-0108", practiceArea: "Personal Injury", caseType: "Truck Accident", description: "T-boned by a freight truck that ran a red light. Multiple fractures, two surgeries. Converted to client after signed contingency retainer.", source: "Google Ads", assignedAttorneyId: "u2", status: "Converted", priority: "High", estimatedValue: 240000, createdAt: stampDaysAgo(64, 11, 30), lastContactAt: stampDaysAgo(2, 14, 0) },
  { id: "l13", firstName: "Hassan", lastName: "Yilmaz", email: "hassan.yilmaz@mail.com", phone: "(678) 555-0171", practiceArea: "Immigration", caseType: "Asylum", description: "Asylum petition with strong documentary evidence. Converted after consultation; I-589 filed and receipt received.", source: "Referral", assignedAttorneyId: "u3", status: "Converted", priority: "Medium", estimatedValue: 11000, createdAt: stampDaysAgo(48, 9, 45), lastContactAt: stampDaysAgo(4, 10, 20) },
  { id: "l14", firstName: "George", lastName: "Pappas", email: "george.pappas@mail.com", phone: "(770) 555-0166", practiceArea: "Personal Injury", caseType: "Auto Accident", description: "Minor fender bender, soft-tissue claim under $4k. Chose a high-volume settlement firm.", source: "Walk-in", assignedAttorneyId: "u2", status: "Lost", priority: "Low", estimatedValue: 4000, createdAt: stampDaysAgo(21, 13, 0), lastContactAt: stampDaysAgo(15, 12, 0), lostReason: "Chose another firm" },
  { id: "l15", firstName: "Olivia", lastName: "Grant", email: "olivia.grant@mail.com", phone: "(404) 555-0155", practiceArea: "Estate Planning", caseType: "Simple Will", description: "Wanted a simple will package. Price-sensitive; went with an online service.", source: "Social Media", assignedAttorneyId: "u3", status: "Lost", priority: "Low", estimatedValue: 900, createdAt: stampDaysAgo(18, 10, 10), lastContactAt: stampDaysAgo(12, 16, 0), lostReason: "Price" },
];
// __PART2__
