import {
  DB, Lead, Contact, Client, Matter, TaskItem, Appointment, DocFile,
  Communication, Note, Activity, Retainer, TimeEntry, Expense, Invoice,
  NotificationItem, AutomationRule, IntakeForm, IntakeSubmission,
  ConflictCheck, AuditLog, User,
} from "./types";
import { addDaysISO, stampDaysAgo, stampDaysAhead } from "./utils";

const users: User[] = [
  { id: "u1", name: "Amira Shah", email: "amira@lawflow.co", role: "super_admin", title: "Managing Partner", color: "#2f6bff", hourlyRate: 450, twoFactorEnabled: true, lastActive: stampDaysAgo(0, 8, 45) },
  { id: "u2", name: "Daniel Reyes", email: "daniel@lawflow.co", role: "attorney", title: "Senior Attorney — Personal Injury", color: "#2f9e77", hourlyRate: 385, twoFactorEnabled: true, lastActive: stampDaysAgo(0, 9, 10) },
  { id: "u3", name: "Grace Okafor", email: "grace@lawflow.co", role: "attorney", title: "Attorney — Family & Immigration", color: "#7a5af8", hourlyRate: 340, twoFactorEnabled: false, lastActive: stampDaysAgo(0, 7, 55) },
  { id: "u9", name: "Victoria Chen", email: "victoria@lawflow.co", role: "attorney", title: "Attorney — Criminal & Business", color: "#c9862b", hourlyRate: 360, twoFactorEnabled: true, lastActive: stampDaysAgo(1, 17, 20) },
  { id: "u4", name: "Marcus Webb", email: "marcus@lawflow.co", role: "paralegal", title: "Senior Paralegal", color: "#0e9bb5", hourlyRate: 150, twoFactorEnabled: false, lastActive: stampDaysAgo(0, 9, 30) },
  { id: "u5", name: "Lena Kowalski", email: "lena@lawflow.co", role: "intake_manager", title: "Intake Manager", color: "#b065d8", hourlyRate: 95, twoFactorEnabled: false, lastActive: stampDaysAgo(0, 8, 15) },
  { id: "u6", name: "Tom Bradley", email: "tom@lawflow.co", role: "receptionist", title: "Front Desk", color: "#5d6b8c", hourlyRate: 45, twoFactorEnabled: false, lastActive: stampDaysAgo(0, 8, 5) },
  { id: "u7", name: "Rachel Donovan", email: "rachel.donovan@mail.com", role: "client", title: "Client", color: "#d05555", hourlyRate: 0, clientId: "c1", twoFactorEnabled: false, lastActive: stampDaysAgo(1, 19, 40) },
  { id: "u8", name: "Hassan Yilmaz", email: "hassan.yilmaz@mail.com", role: "client", title: "Client", color: "#2f9e77", hourlyRate: 0, clientId: "c2", twoFactorEnabled: false, lastActive: stampDaysAgo(2, 11, 5) },
];

const leads: Lead[] = [
  { id: "l1", firstName: "Marcus", lastName: "Delgado", email: "marcus.delgado@mail.com", phone: "(404) 555-0182", practiceArea: "Personal Injury", caseType: "Auto Accident", description: "Rear-ended at a red light on I-285 by a commercial van. Herniated disc at L4-L5, ongoing physical therapy. Other driver's insurer is disputing liability.", source: "Google Ads", assignedAttorneyId: "u2", intakeManagerId: "u5", status: "New Lead", priority: "High", estimatedValue: 85000, createdAt: stampDaysAgo(1, 9, 12), lastContactAt: stampDaysAgo(1, 9, 40), nextFollowUpAt: addDaysISO(0) },
  { id: "l2", firstName: "Priya", lastName: "Nair", email: "priya.nair@mail.com", phone: "(678) 555-0144", practiceArea: "Immigration", caseType: "H-1B Transfer", description: "H-1B transfer from current employer plus H-4 EAD for spouse. Current visa expires in 5 months; employer change already in motion.", source: "Referral", assignedAttorneyId: "u3", intakeManagerId: "u5", status: "New Lead", priority: "Medium", estimatedValue: 6500, createdAt: stampDaysAgo(0, 8, 5), lastContactAt: stampDaysAgo(0, 8, 5), nextFollowUpAt: addDaysISO(1) },
  { id: "l3", firstName: "Sofia", lastName: "Marino", email: "sofia.marino@mail.com", phone: "(770) 555-0119", practiceArea: "Family Law", caseType: "Child Custody", description: "Seeking primary custody of two children (ages 6 and 9). Ex-spouse relocated out of county without notice. Existing temporary order in place.", source: "Website Form", assignedAttorneyId: "u3", intakeManagerId: "u5", status: "Contacted", priority: "High", estimatedValue: 12000, createdAt: stampDaysAgo(3, 14, 20), lastContactAt: stampDaysAgo(1, 11, 5), nextFollowUpAt: addDaysISO(0) },
  { id: "l4", firstName: "Jamal", lastName: "Carter", email: "jamal.carter@mail.com", phone: "(404) 555-0177", practiceArea: "Criminal Defense", caseType: "Drug Possession", description: "First-offense felony possession charge. Questions about search legality during traffic stop. Arraignment scheduled in two weeks.", source: "Avvo", assignedAttorneyId: "u9", intakeManagerId: "u5", status: "Contacted", priority: "High", estimatedValue: 9500, createdAt: stampDaysAgo(4, 16, 45), lastContactAt: stampDaysAgo(2, 10, 30), nextFollowUpAt: addDaysISO(1) },
  { id: "l5", firstName: "Elena", lastName: "Petrova", email: "elena@petrovafoods.com", phone: "(678) 555-0161", practiceArea: "Business Law", caseType: "Breach of Contract", description: "Vendor failed to deliver per supply agreement, causing ~$60k in losses. Contract has arbitration clause. Wants demand letter sent this month.", source: "Referral", assignedAttorneyId: "u9", status: "Qualified", priority: "Medium", estimatedValue: 22000, createdAt: stampDaysAgo(6, 13, 10), lastContactAt: stampDaysAgo(2, 15, 0), nextFollowUpAt: addDaysISO(2) },
  { id: "l6", firstName: "David", lastName: "Osei", email: "david.osei@mail.com", phone: "(470) 555-0139", practiceArea: "Estate Planning", caseType: "Revocable Trust", description: "Blended family, needs revocable living trust plus updated wills and healthcare directives. Owns two properties and a small business.", source: "Website Form", assignedAttorneyId: "u3", status: "Qualified", priority: "Low", estimatedValue: 4800, createdAt: stampDaysAgo(7, 10, 0), lastContactAt: stampDaysAgo(3, 9, 25), nextFollowUpAt: addDaysISO(3) },
  { id: "l7", firstName: "Angela", lastName: "Brooks", email: "angela.brooks@mail.com", phone: "(404) 555-0126", practiceArea: "Personal Injury", caseType: "Slip and Fall", description: "Slipped on unmarked wet floor at a grocery store. Fractured wrist, out of work 6 weeks. Store incident report exists.", source: "Google Ads", assignedAttorneyId: "u2", intakeManagerId: "u5", status: "Consultation Scheduled", priority: "Medium", estimatedValue: 35000, createdAt: stampDaysAgo(5, 11, 50), lastContactAt: stampDaysAgo(1, 14, 15), nextFollowUpAt: addDaysISO(1) },
  { id: "l8", firstName: "Kevin", lastName: "O'Rourke", email: "kevin.orourke@mail.com", phone: "(678) 555-0158", practiceArea: "Criminal Defense", caseType: "DUI", description: "Second DUI within 5 years. Refused breathalyzer; license suspension hearing pending. Needs representation for both administrative and criminal proceedings.", source: "Bar Association", assignedAttorneyId: "u9", status: "Consultation Scheduled", priority: "Urgent", estimatedValue: 12000, createdAt: stampDaysAgo(2, 17, 30), lastContactAt: stampDaysAgo(0, 9, 5), nextFollowUpAt: addDaysISO(0) },
  { id: "l9", firstName: "Mariana", lastName: "Flores", email: "mariana.flores@mail.com", phone: "(770) 555-0147", practiceArea: "Immigration", caseType: "Asylum", description: "Asylum application, entered US 8 months ago. One-year filing deadline approaching. Has supporting affidavits and country-condition evidence.", source: "Referral", assignedAttorneyId: "u3", intakeManagerId: "u5", status: "Consultation Completed", priority: "Urgent", estimatedValue: 9000, createdAt: stampDaysAgo(9, 15, 20), lastContactAt: stampDaysAgo(1, 16, 45), nextFollowUpAt: addDaysISO(0) },
  { id: "l10", firstName: "Robert", lastName: "Lindqvist", email: "robert@lindqvistdev.com", phone: "(404) 555-0193", practiceArea: "Business Law", caseType: "Partnership Dispute", description: "50/50 partner is diverting company opportunities to a side entity. Operating agreement has non-compete language. Seeking buyout or dissolution strategy.", source: "Website Form", assignedAttorneyId: "u9", status: "Retainer Sent", priority: "High", estimatedValue: 45000, createdAt: stampDaysAgo(11, 10, 40), lastContactAt: stampDaysAgo(2, 13, 30), nextFollowUpAt: addDaysISO(1) },
  { id: "l11", firstName: "Tanya", lastName: "Becker", email: "tanya.becker@mail.com", phone: "(470) 555-0112", practiceArea: "Family Law", caseType: "Divorce", description: "Divorce involving business valuation of a dental practice and two rental properties. Signed retainer returned yesterday — ready to onboard.", source: "Referral", assignedAttorneyId: "u3", intakeManagerId: "u5", status: "Retainer Signed", priority: "High", estimatedValue: 25000, createdAt: stampDaysAgo(14, 12, 15), lastContactAt: stampDaysAgo(1, 10, 0), nextFollowUpAt: addDaysISO(0) },
  { id: "l12", firstName: "Rachel", lastName: "Donovan", email: "rachel.donovan@mail.com", phone: "(404) 555-0108", practiceArea: "Personal Injury", caseType: "Truck Accident", description: "T-boned by a freight truck that ran a red light. Multiple fractures, two surgeries. Converted to client after signed contingency retainer.", source: "Google Ads", assignedAttorneyId: "u2", status: "Converted", priority: "High", estimatedValue: 240000, createdAt: stampDaysAgo(64, 11, 30), lastContactAt: stampDaysAgo(2, 14, 0) },
  { id: "l13", firstName: "Hassan", lastName: "Yilmaz", email: "hassan.yilmaz@mail.com", phone: "(678) 555-0171", practiceArea: "Immigration", caseType: "Asylum", description: "Asylum petition with strong documentary evidence. Converted after consultation; I-589 filed and receipt received.", source: "Referral", assignedAttorneyId: "u3", status: "Converted", priority: "Medium", estimatedValue: 11000, createdAt: stampDaysAgo(48, 9, 45), lastContactAt: stampDaysAgo(4, 10, 20) },
  { id: "l14", firstName: "George", lastName: "Pappas", email: "george.pappas@mail.com", phone: "(770) 555-0166", practiceArea: "Personal Injury", caseType: "Auto Accident", description: "Minor fender bender, soft-tissue claim under $4k. Chose a high-volume settlement firm.", source: "Walk-in", assignedAttorneyId: "u2", status: "Lost", priority: "Low", estimatedValue: 4000, createdAt: stampDaysAgo(21, 13, 0), lastContactAt: stampDaysAgo(15, 12, 0), lostReason: "Chose another firm" },
  { id: "l15", firstName: "Olivia", lastName: "Grant", email: "olivia.grant@mail.com", phone: "(404) 555-0155", practiceArea: "Estate Planning", caseType: "Simple Will", description: "Wanted a simple will package. Price-sensitive; went with an online service.", source: "Social Media", assignedAttorneyId: "u3", status: "Lost", priority: "Low", estimatedValue: 900, createdAt: stampDaysAgo(18, 10, 10), lastContactAt: stampDaysAgo(12, 16, 0), lostReason: "Price" },
];
const clients: Client[] = [
  { id: "c1", name: "Rachel Donovan", email: "rachel.donovan@mail.com", phone: "(404) 555-0108", leadId: "l12", practiceArea: "Personal Injury", attorneyId: "u2", since: stampDaysAgo(58, 10, 0), status: "Active", address: "1187 Peachtree St NE, Atlanta, GA" },
  { id: "c2", name: "Hassan Yilmaz", email: "hassan.yilmaz@mail.com", phone: "(678) 555-0171", leadId: "l13", practiceArea: "Immigration", attorneyId: "u3", since: stampDaysAgo(44, 10, 0), status: "Active", address: "452 Buford Hwy, Doraville, GA" },
  { id: "c3", name: "Brightline Logistics LLC", email: "legal@brightlinelogistics.com", phone: "(404) 555-0190", company: "Brightline Logistics LLC", practiceArea: "Business Law", attorneyId: "u9", since: stampDaysAgo(210, 10, 0), status: "Active", address: "2300 Marietta Blvd NW, Atlanta, GA" },
  { id: "c4", name: "Karen Mitchell", email: "karen.mitchell@mail.com", phone: "(770) 555-0121", practiceArea: "Family Law", attorneyId: "u3", since: stampDaysAgo(96, 10, 0), status: "Active", address: "88 Roswell Rd, Sandy Springs, GA" },
  { id: "c5", name: "Deshawn Miller", email: "deshawn.miller@mail.com", phone: "(404) 555-0133", practiceArea: "Criminal Defense", attorneyId: "u9", since: stampDaysAgo(38, 10, 0), status: "Active" },
  { id: "c6", name: "Ingrid Halvorsen", email: "ingrid.h@mail.com", phone: "(470) 555-0104", practiceArea: "Estate Planning", attorneyId: "u3", since: stampDaysAgo(25, 10, 0), status: "Active", address: "12 Lakeview Dr, Decatur, GA" },
  { id: "c7", name: "Apex Components Inc", email: "contracts@apexcomponents.com", phone: "(678) 555-0188", company: "Apex Components Inc", practiceArea: "Business Law", attorneyId: "u9", since: stampDaysAgo(150, 10, 0), status: "Active" },
  { id: "c8", name: "Rosa Jimenez", email: "rosa.jimenez@mail.com", phone: "(770) 555-0199", practiceArea: "Personal Injury", attorneyId: "u2", since: stampDaysAgo(320, 10, 0), status: "Active", address: "741 Buford Dr, Lawrenceville, GA" },
];

const matters: Matter[] = [
  { id: "m1", name: "Donovan v. Crossway Freight", number: "PI-2025-0142", clientId: "c1", practiceArea: "Personal Injury", attorneyId: "u2", paralegalId: "u4", status: "Discovery", priority: "High", openDate: addDaysISO(-55), court: "Superior Court of Fulton County", opposingParty: "Crossway Freight Lines", nextDeadline: addDaysISO(5), caseValue: 240000, description: "Truck accident liability suit. Client sustained multiple fractures requiring two surgeries. Currently in discovery; defendant disputes signal timing." },
  { id: "m2", name: "Yilmaz Asylum Petition", number: "IMM-2025-0031", clientId: "c2", practiceArea: "Immigration", attorneyId: "u3", paralegalId: "u4", status: "Open", priority: "High", openDate: addDaysISO(-40), court: "EOIR Atlanta Immigration Court", nextDeadline: addDaysISO(12), caseValue: 11000, description: "Affirmative asylum application (I-589) with supporting affidavits and country-condition reports. Biometrics completed." },
  { id: "m3", name: "Brightline v. Apex Components", number: "BUS-2024-0087", clientId: "c3", practiceArea: "Business Law", attorneyId: "u9", paralegalId: "u4", status: "Negotiation", priority: "Medium", openDate: addDaysISO(-200), opposingParty: "Apex Components Inc", nextDeadline: addDaysISO(9), caseValue: 180000, description: "Breach of supply agreement — failure to deliver conforming goods. Demand letter sent; parties exchanging settlement terms." },
  { id: "m4", name: "Mitchell Divorce & Custody", number: "FAM-2025-0019", clientId: "c4", practiceArea: "Family Law", attorneyId: "u3", status: "Court Pending", priority: "High", openDate: addDaysISO(-90), court: "Fulton County Family Division", opposingParty: "Paul Mitchell", nextDeadline: addDaysISO(3), caseValue: 30000, description: "Contested divorce with custody dispute over two minors. Temporary hearing concluded; final hearing set." },
  { id: "m5", name: "State v. Miller", number: "CRI-2025-0052", clientId: "c5", practiceArea: "Criminal Defense", attorneyId: "u9", status: "Discovery", priority: "Urgent", openDate: addDaysISO(-33), court: "Fulton County Superior Court — Criminal Division", nextDeadline: addDaysISO(6), caseValue: 15000, description: "Felony possession charge. Motion to suppress filed challenging the traffic stop. Awaiting discovery from the DA's office." },
  { id: "m6", name: "Halvorsen Revocable Trust", number: "EST-2025-0007", clientId: "c6", practiceArea: "Estate Planning", attorneyId: "u3", status: "Open", priority: "Low", openDate: addDaysISO(-22), nextDeadline: addDaysISO(20), caseValue: 5500, description: "Revocable living trust, pour-over wills, and healthcare directives for a blended family with two properties." },
  { id: "m7", name: "Jimenez v. SaveMart", number: "PI-2024-0108", clientId: "c8", practiceArea: "Personal Injury", attorneyId: "u2", paralegalId: "u4", status: "Settlement", priority: "Medium", openDate: addDaysISO(-310), opposingParty: "SaveMart Stores Inc", nextDeadline: addDaysISO(8), caseValue: 95000, description: "Slip and fall with fractured wrist. Mediation produced an offer at $82,500; client considering counter at $90,000." },
  { id: "m8", name: "Apex Components Trademark Filing", number: "BUS-2025-0015", clientId: "c7", practiceArea: "Business Law", attorneyId: "u9", status: "Open", priority: "Low", openDate: addDaysISO(-15), nextDeadline: addDaysISO(30), caseValue: 7500, description: "USPTO trademark application for component product line, plus office-action response strategy." },
  { id: "m9", name: "State v. Tran", number: "CRI-2024-0033", clientId: "c5", practiceArea: "Criminal Defense", attorneyId: "u9", status: "Closed", priority: "Low", openDate: addDaysISO(-400), closeDate: addDaysISO(-180), court: "DeKalb County Recorders Court", caseValue: 6000, description: "Misdemeanor charge — dismissed after completion of diversion program." },
];

const contacts: Contact[] = [
  { id: "k1", type: "Opposing Counsel", name: "Sarah Friedman", email: "sfriedman@friedmanhall.com", phone: "(404) 555-0201", company: "Friedman & Hall PC", matterId: "m1", notes: "Defense counsel for Crossway Freight. Responsive, prefers email." },
  { id: "k2", type: "Opposing Counsel", name: "Gregory Hale", email: "ghale@halelaw.com", phone: "(404) 555-0214", company: "Hale & Associates", matterId: "m3", notes: "Represents Apex Components in supply dispute." },
  { id: "k3", type: "Witness", name: "Denise Whitfield", email: "d.whitfield@mail.com", phone: "(770) 555-0220", matterId: "m1", notes: "Eyewitness to the Donovan collision; stopped at same light." },
  { id: "k4", type: "Witness", name: "Officer Ray Kowalski (APD)", email: "rkowalski@atlantapd.gov", phone: "(404) 555-0233", matterId: "m5", notes: "Arresting officer in State v. Miller." },
  { id: "k5", type: "Referral Partner", name: "Dr. Alan Meyer", email: "ameyer@peachtreeortho.com", phone: "(404) 555-0241", company: "Peachtree Orthopedics", notes: "Orthopedic surgeon; refers PI patients and provides expert opinions." },
  { id: "k6", type: "Referral Partner", name: "Rosetta Translation Services", email: "projects@rosettats.com", phone: "(678) 555-0250", company: "Rosetta TS", notes: "Certified translations for immigration filings." },
  { id: "k7", type: "Company", name: "Crossway Freight Lines", email: "claims@crosswayfreight.com", phone: "(912) 555-0266", matterId: "m1", notes: "Defendant in Donovan matter. Regional freight carrier." },
  { id: "k8", type: "Company", name: "SaveMart Stores Inc", email: "risk@savemart.com", phone: "(770) 555-0277", matterId: "m7", notes: "Defendant in Jimenez slip-and-fall." },
  { id: "k9", type: "Opposing Counsel", name: "ADA Lisa Moreno", email: "lmoreno@fultonda.org", phone: "(404) 555-0288", company: "Fulton County DA Office", matterId: "m5", notes: "Assistant DA assigned to State v. Miller." },
  { id: "k10", type: "Client", name: "Karen Mitchell", email: "karen.mitchell@mail.com", phone: "(770) 555-0121", matterId: "m4" },
  { id: "k11", type: "Attorney", name: "Daniel Reyes", email: "daniel@lawflow.co", phone: "(404) 555-0300", company: "LawFlow CRM Demo Firm" },
  { id: "k12", type: "Lead", name: "Marcus Delgado", email: "marcus.delgado@mail.com", phone: "(404) 555-0182" },
];

const tasks: TaskItem[] = [
  { id: "t1", title: "Draft demand letter — Donovan v. Crossway", assigneeId: "u2", matterId: "m1", priority: "High", dueDate: addDaysISO(2), status: "In Progress", notes: "Include surgical records and lost-wage statement.", reminderAt: addDaysISO(1), createdAt: stampDaysAgo(3) },
  { id: "t2", title: "Order updated medical records — Jimenez", assigneeId: "u4", matterId: "m7", priority: "Medium", dueDate: addDaysISO(-1), status: "To Do", notes: "Ortho follow-up from last month still missing.", createdAt: stampDaysAgo(6) },
  { id: "t3", title: "Prepare I-589 supplementary evidence index", assigneeId: "u4", matterId: "m2", priority: "High", dueDate: addDaysISO(4), status: "In Progress", createdAt: stampDaysAgo(2) },
  { id: "t4", title: "Draft responses to Apex interrogatories", assigneeId: "u9", matterId: "m3", priority: "Medium", dueDate: addDaysISO(7), status: "To Do", createdAt: stampDaysAgo(1) },
  { id: "t5", title: "Call Marcus Delgado — new lead follow-up", assigneeId: "u5", leadId: "l1", priority: "High", dueDate: addDaysISO(0), status: "To Do", notes: "Confirm PIP carrier and treating physician.", reminderAt: addDaysISO(0), createdAt: stampDaysAgo(1) },
  { id: "t6", title: "Confirm consultation details — Angela Brooks", assigneeId: "u6", leadId: "l7", priority: "Medium", dueDate: addDaysISO(0), status: "Completed", createdAt: stampDaysAgo(1) },
  { id: "t7", title: "Send engagement letter — Lindqvist partnership dispute", assigneeId: "u9", leadId: "l10", priority: "High", dueDate: addDaysISO(-2), status: "Completed", createdAt: stampDaysAgo(4) },
  { id: "t8", title: "Review custody evaluation report — Mitchell", assigneeId: "u3", matterId: "m4", priority: "Urgent", dueDate: addDaysISO(1), status: "In Progress", notes: "Final hearing prep; flag concerns on page 14.", createdAt: stampDaysAgo(2) },
  { id: "t9", title: "File motion to suppress — State v. Miller", assigneeId: "u9", matterId: "m5", priority: "Urgent", dueDate: addDaysISO(6), status: "To Do", createdAt: stampDaysAgo(1) },
  { id: "t10", title: "Assemble trust execution packet — Halvorsen", assigneeId: "u4", matterId: "m6", priority: "Low", dueDate: addDaysISO(10), status: "To Do", createdAt: stampDaysAgo(3) },
  { id: "t11", title: "Follow up on retainer — Robert Lindqvist", assigneeId: "u5", leadId: "l10", priority: "High", dueDate: addDaysISO(1), status: "To Do", reminderAt: addDaysISO(1), createdAt: stampDaysAgo(1) },
  { id: "t12", title: "Prepare asylum filing timeline — Mariana Flores", assigneeId: "u3", leadId: "l9", priority: "Urgent", dueDate: addDaysISO(0), status: "To Do", notes: "One-year deadline is approaching fast.", createdAt: stampDaysAgo(0) },
  { id: "t13", title: "Upload signed retainer — Tanya Becker", assigneeId: "u5", leadId: "l11", priority: "High", dueDate: addDaysISO(-1), status: "Completed", createdAt: stampDaysAgo(2) },
  { id: "t14", title: "Schedule mediation date — Jimenez v. SaveMart", assigneeId: "u2", matterId: "m7", priority: "Medium", dueDate: addDaysISO(5), status: "To Do", createdAt: stampDaysAgo(2) },
  { id: "t15", title: "Conflict check — Petrova vendor dispute", assigneeId: "u5", leadId: "l5", priority: "Medium", dueDate: addDaysISO(-3), status: "Completed", createdAt: stampDaysAgo(5) },
  { id: "t16", title: "Prepare USCIS cover letter — Yilmaz", assigneeId: "u4", matterId: "m2", priority: "Medium", dueDate: addDaysISO(3), status: "To Do", createdAt: stampDaysAgo(1) },
];
const appointments: Appointment[] = [
  { id: "a1", title: "Consultation — Kevin O'Rourke (DUI)", type: "Consultation", date: addDaysISO(0), startTime: "14:30", endTime: "15:15", leadId: "l8", attendeeIds: ["u9", "u5"], location: "Office — Room 3", notes: "Bring citation and ALS hearing notice." },
  { id: "a2", title: "Case review — weekly litigation standup", type: "Internal Meeting", date: addDaysISO(0), startTime: "09:00", endTime: "09:45", attendeeIds: ["u1", "u2", "u3", "u9", "u4"], location: "Conference Room A" },
  { id: "a3", title: "Client meeting — Rachel Donovan case update", type: "Client Meeting", date: addDaysISO(0), startTime: "11:00", endTime: "11:45", matterId: "m1", clientId: "c1", attendeeIds: ["u2", "u4"], location: "Office — Room 1" },
  { id: "a4", title: "Consultation — Angela Brooks (slip & fall)", type: "Consultation", date: addDaysISO(1), startTime: "10:00", endTime: "10:45", leadId: "l7", attendeeIds: ["u2", "u5"], location: "Video call" },
  { id: "a5", title: "Arraignment — State v. Miller", type: "Court Hearing", date: addDaysISO(2), startTime: "09:30", endTime: "11:00", matterId: "m5", clientId: "c5", attendeeIds: ["u9"], location: "Fulton County Superior Court, Courtroom 4B" },
  { id: "a6", title: "Deposition — Denise Whitfield (eyewitness)", type: "Deposition", date: addDaysISO(6), startTime: "13:00", endTime: "15:00", matterId: "m1", attendeeIds: ["u2", "u4"], location: "Friedman & Hall PC offices" },
  { id: "a7", title: "Filing deadline — Discovery cutoff (Brightline)", type: "Filing Deadline", date: addDaysISO(9), startTime: "17:00", endTime: "17:00", matterId: "m3", attendeeIds: ["u9"] },
  { id: "a8", title: "Final hearing — Mitchell custody", type: "Court Hearing", date: addDaysISO(3), startTime: "10:00", endTime: "12:00", matterId: "m4", clientId: "c4", attendeeIds: ["u3"], location: "Fulton County Family Division" },
  { id: "a9", title: "Follow-up call — Sofia Marino", type: "Follow-up", date: addDaysISO(0), startTime: "16:00", endTime: "16:20", leadId: "l3", attendeeIds: ["u5"], location: "Phone" },
  { id: "a10", title: "I-589 evidence submission deadline — Yilmaz", type: "Filing Deadline", date: addDaysISO(12), startTime: "17:00", endTime: "17:00", matterId: "m2", attendeeIds: ["u3", "u4"] },
  { id: "a11", title: "Mediation — Jimenez v. SaveMart", type: "Client Meeting", date: addDaysISO(8), startTime: "09:00", endTime: "13:00", matterId: "m7", clientId: "c8", attendeeIds: ["u2"], location: "Atlanta Mediation Center" },
  { id: "a12", title: "Trust signing — Ingrid Halvorsen", type: "Client Meeting", date: addDaysISO(14), startTime: "15:00", endTime: "16:00", matterId: "m6", clientId: "c6", attendeeIds: ["u3"], location: "Office — Room 2" },
  { id: "a13", title: "Consultation debrief — Mariana Flores", type: "Follow-up", date: addDaysISO(-1), startTime: "11:00", endTime: "11:30", leadId: "l9", attendeeIds: ["u3", "u5"] },
  { id: "a14", title: "Quarterly marketing review", type: "Internal Meeting", date: addDaysISO(5), startTime: "14:00", endTime: "15:00", attendeeIds: ["u1", "u5"], location: "Conference Room A" },
];

const documents: DocFile[] = [
  { id: "d1", name: "Police Report — Donovan.pdf", folder: "PI-2025-0142 Donovan", matterId: "m1", clientId: "c1", uploadedById: "u4", uploadedAt: stampDaysAgo(20, 10, 15), sizeKb: 2410, ext: "pdf", versions: [{ v: 1, at: stampDaysAgo(20, 10, 15), byId: "u4" }] },
  { id: "d2", name: "Medical Records — Peachtree Ortho.pdf", folder: "PI-2025-0142 Donovan", matterId: "m1", clientId: "c1", uploadedById: "u4", uploadedAt: stampDaysAgo(12, 15, 40), sizeKb: 18940, ext: "pdf", versions: [{ v: 1, at: stampDaysAgo(15, 9, 0), byId: "u4" }, { v: 2, at: stampDaysAgo(12, 15, 40), byId: "u4", note: "Added surgical reports" }] },
  { id: "d3", name: "Demand Letter — Draft v2.docx", folder: "PI-2025-0142 Donovan", matterId: "m1", clientId: "c1", uploadedById: "u2", uploadedAt: stampDaysAgo(2, 11, 25), sizeKb: 88, ext: "docx", versions: [{ v: 1, at: stampDaysAgo(5, 16, 0), byId: "u2" }, { v: 2, at: stampDaysAgo(2, 11, 25), byId: "u2", note: "Revised damages section" }] },
  { id: "d4", name: "I-589 Application — Yilmaz (filed).pdf", folder: "IMM-2025-0031 Yilmaz", matterId: "m2", clientId: "c2", uploadedById: "u3", uploadedAt: stampDaysAgo(30, 14, 0), sizeKb: 3120, ext: "pdf", versions: [{ v: 1, at: stampDaysAgo(30, 14, 0), byId: "u3" }] },
  { id: "d5", name: "Country Conditions Evidence Bundle.pdf", folder: "IMM-2025-0031 Yilmaz", matterId: "m2", clientId: "c2", uploadedById: "u4", uploadedAt: stampDaysAgo(8, 10, 45), sizeKb: 22100, ext: "pdf", versions: [{ v: 1, at: stampDaysAgo(8, 10, 45), byId: "u4" }] },
  { id: "d6", name: "Supply Agreement — Brightline v Apex.pdf", folder: "BUS-2024-0087 Brightline", matterId: "m3", clientId: "c3", uploadedById: "u9", uploadedAt: stampDaysAgo(190, 9, 30), sizeKb: 640, ext: "pdf", versions: [{ v: 1, at: stampDaysAgo(190, 9, 30), byId: "u9" }] },
  { id: "d7", name: "Interrogatories — Apex (received).pdf", folder: "BUS-2024-0087 Brightline", matterId: "m3", clientId: "c3", uploadedById: "u4", uploadedAt: stampDaysAgo(6, 13, 20), sizeKb: 412, ext: "pdf", versions: [{ v: 1, at: stampDaysAgo(6, 13, 20), byId: "u4" }] },
  { id: "d8", name: "Custody Evaluation Report.pdf", folder: "FAM-2025-0019 Mitchell", matterId: "m4", clientId: "c4", uploadedById: "u3", uploadedAt: stampDaysAgo(4, 16, 10), sizeKb: 5280, ext: "pdf", versions: [{ v: 1, at: stampDaysAgo(4, 16, 10), byId: "u3" }] },
  { id: "d9", name: "Motion to Suppress — Draft.docx", folder: "CRI-2025-0052 Miller", matterId: "m5", clientId: "c5", uploadedById: "u9", uploadedAt: stampDaysAgo(1, 17, 45), sizeKb: 96, ext: "docx", versions: [{ v: 1, at: stampDaysAgo(3, 12, 0), byId: "u9" }, { v: 2, at: stampDaysAgo(1, 17, 45), byId: "u9", note: "Added Fourth Amendment case law" }] },
  { id: "d10", name: "Halvorsen Trust Instrument v3.docx", folder: "EST-2025-0007 Halvorsen", matterId: "m6", clientId: "c6", uploadedById: "u3", uploadedAt: stampDaysAgo(3, 11, 0), sizeKb: 120, ext: "docx", versions: [{ v: 1, at: stampDaysAgo(15, 10, 0), byId: "u3" }, { v: 2, at: stampDaysAgo(9, 10, 0), byId: "u3" }, { v: 3, at: stampDaysAgo(3, 11, 0), byId: "u3", note: "Client-requested guardian changes" }] },
  { id: "d11", name: "SaveMart Settlement Offer.pdf", folder: "PI-2024-0108 Jimenez", matterId: "m7", clientId: "c8", uploadedById: "u2", uploadedAt: stampDaysAgo(5, 15, 30), sizeKb: 74, ext: "pdf", versions: [{ v: 1, at: stampDaysAgo(5, 15, 30), byId: "u2" }] },
  { id: "d12", name: "Retainer Agreement — Lindqvist.pdf", folder: "Retainers", leadId: "l10", uploadedById: "u9", uploadedAt: stampDaysAgo(2, 13, 0), sizeKb: 210, ext: "pdf", versions: [{ v: 1, at: stampDaysAgo(2, 13, 0), byId: "u9" }] },
  { id: "d13", name: "Retainer Agreement — Becker (signed).pdf", folder: "Retainers", leadId: "l11", uploadedById: "u5", uploadedAt: stampDaysAgo(1, 9, 40), sizeKb: 228, ext: "pdf", versions: [{ v: 1, at: stampDaysAgo(1, 9, 40), byId: "u5" }] },
  { id: "d14", name: "Intake Form — Marcus Delgado.pdf", folder: "Intake Forms", leadId: "l1", uploadedById: "u5", uploadedAt: stampDaysAgo(1, 9, 20), sizeKb: 64, ext: "pdf", versions: [{ v: 1, at: stampDaysAgo(1, 9, 20), byId: "u5" }] },
  { id: "d15", name: "Trademark Specimen — Apex.png", folder: "BUS-2025-0015 Apex TM", matterId: "m8", clientId: "c7", uploadedById: "u9", uploadedAt: stampDaysAgo(7, 10, 5), sizeKb: 840, ext: "png", versions: [{ v: 1, at: stampDaysAgo(7, 10, 5), byId: "u9" }] },
  { id: "d16", name: "Engagement Letter Template.docx", folder: "Templates", uploadedById: "u1", uploadedAt: stampDaysAgo(60, 10, 0), sizeKb: 42, ext: "docx", versions: [{ v: 1, at: stampDaysAgo(60, 10, 0), byId: "u1" }] },
];
const communications: Communication[] = [
  { id: "cm1", type: "Email", direction: "Inbound", fromName: "Marcus Delgado", toName: "Lena Kowalski", subject: "Re: Your injury claim consultation", body: "Thanks for the quick response. I have the police report and my MRI results ready to send over. The insurance adjuster keeps calling me — should I talk to them?", at: stampDaysAgo(0, 8, 55), leadId: "l1" },
  { id: "cm2", type: "Phone Call", direction: "Outbound", fromName: "Lena Kowalski", toName: "Sofia Marino", body: "Discussed custody timeline and temporary order. Sofia will email the existing court order before Friday. Consultation slot offered for next week.", at: stampDaysAgo(1, 11, 5), leadId: "l3" },
  { id: "cm3", type: "Email", direction: "Outbound", fromName: "Daniel Reyes", toName: "Sarah Friedman", subject: "Donovan v. Crossway — discovery schedule", body: "Confirming the Whitfield deposition for next week and requesting defendant's driver logs within 10 days per our meet-and-confer.", at: stampDaysAgo(1, 15, 20), matterId: "m1", clientId: "c1", userId: "u2" },
  { id: "cm4", type: "SMS", direction: "Inbound", fromName: "Rachel Donovan", toName: "LawFlow Firm", body: "Hi, is my case update meeting still on for tomorrow at 11?", at: stampDaysAgo(1, 18, 40), matterId: "m1", clientId: "c1" },
  { id: "cm5", type: "Internal Note", direction: "Internal", fromName: "Grace Okafor", toName: "File", body: "Mitchell final hearing prep: custody evaluator's concerns are mostly about the father's relocation. Prepare direct exam outline.", at: stampDaysAgo(1, 16, 10), matterId: "m4", userId: "u3" },
  { id: "cm6", type: "Email", direction: "Inbound", fromName: "Robert Lindqvist", toName: "Victoria Chen", subject: "Re: Engagement letter", body: "Reviewed the engagement letter with my accountant. One question about the litigation holdback clause, then I'll sign.", at: stampDaysAgo(0, 7, 30), leadId: "l10" },
  { id: "cm7", type: "Phone Call", direction: "Outbound", fromName: "Victoria Chen", toName: "Kevin O'Rourke", body: "Explained ALS hearing process and 30-day permit. Kevin confirmed he can attend the consultation tomorrow with paperwork.", at: stampDaysAgo(0, 9, 5), leadId: "l8" },
  { id: "cm8", type: "Email", direction: "Inbound", fromName: "Hassan Yilmaz", toName: "Grace Okafor", subject: "Biometrics appointment letter", body: "I received the biometrics appointment notice from USCIS. Scan attached. The date works for me.", at: stampDaysAgo(2, 10, 50), matterId: "m2", clientId: "c2" },
  { id: "cm9", type: "Internal Note", direction: "Internal", fromName: "Marcus Webb", toName: "File", body: "Yilmaz evidence bundle: still missing two affidavits. Followed up with translator for certified copies.", at: stampDaysAgo(2, 14, 35), matterId: "m2", userId: "u4" },
  { id: "cm10", type: "Email", direction: "Outbound", fromName: "Lena Kowalski", toName: "Mariana Flores", subject: "Next steps after your consultation", body: "Thank you for meeting with Ms. Okafor. Attached is our engagement letter and the evidence checklist we discussed. The one-year deadline is important — please review this week.", at: stampDaysAgo(1, 16, 45), leadId: "l9" },
  { id: "cm11", type: "SMS", direction: "Outbound", fromName: "LawFlow Firm", toName: "Angela Brooks", body: "Reminder: your consultation with Mr. Reyes is tomorrow at 10:00 AM by video. Reply YES to confirm.", at: stampDaysAgo(0, 8, 0), leadId: "l7" },
  { id: "cm12", type: "Email", direction: "Inbound", fromName: "Tanya Becker", toName: "Lena Kowalski", subject: "Signed retainer attached", body: "Signed retainer attached. Also sending last year's P&L for the practice valuation. Looking forward to getting started.", at: stampDaysAgo(1, 9, 35), leadId: "l11" },
  { id: "cm13", type: "Phone Call", direction: "Inbound", fromName: "Rosa Jimenez", toName: "Daniel Reyes", body: "Discussed the $82,500 offer. Rosa wants to counter at $90,000 and is comfortable waiting one more round.", at: stampDaysAgo(3, 13, 15), matterId: "m7", clientId: "c8" },
  { id: "cm14", type: "Internal Note", direction: "Internal", fromName: "Amira Shah", toName: "File", body: "Reviewed Q3 intake metrics: PI conversion is strong, but response time on web forms slipped to 6h. Flag for automation tuning.", at: stampDaysAgo(4, 11, 0), userId: "u1" },
  { id: "cm15", type: "Email", direction: "Outbound", fromName: "Grace Okafor", toName: "Priya Nair", subject: "H-1B transfer — document checklist", body: "Welcome! Attached is the document checklist for your transfer and H-4 EAD. Please send your current I-797 and recent pay stubs.", at: stampDaysAgo(0, 9, 40), leadId: "l2" },
  { id: "cm16", type: "SMS", direction: "Inbound", fromName: "Deshawn Miller", toName: "LawFlow Firm", body: "Court is still Thursday right? Which courtroom?", at: stampDaysAgo(0, 10, 15), matterId: "m5", clientId: "c5" },
];

const notes: Note[] = [
  { id: "n1", body: "Client's treating physician believes a second surgery is likely. Factor into demand range.", at: stampDaysAgo(6, 12, 0), authorId: "u2", matterId: "m1" },
  { id: "n2", body: "Strong liability facts; dashcam footage preserved by witness.", at: stampDaysAgo(18, 15, 0), authorId: "u4", matterId: "m1" },
  { id: "n3", body: "Flores consultation: credible fear indicators present. Prioritize one-year deadline.", at: stampDaysAgo(1, 17, 20), authorId: "u3", leadId: "l9" },
  { id: "n4", body: "Delgado: commercial policy limits likely $1M. Verify carrier before consultation.", at: stampDaysAgo(0, 9, 50), authorId: "u5", leadId: "l1" },
  { id: "n5", body: "Becker onboarding checklist started. Waiting on practice financials for valuation expert.", at: stampDaysAgo(1, 10, 30), authorId: "u3", leadId: "l11" },
  { id: "n6", body: "Miller: dashcam request sent to APD under open records.", at: stampDaysAgo(5, 14, 0), authorId: "u9", matterId: "m5" },
  { id: "n7", body: "Halvorsen wants trust to include special-needs provisions for grandson.", at: stampDaysAgo(9, 11, 0), authorId: "u3", matterId: "m6" },
  { id: "n8", body: "Brightline: keep negotiation posture firm on delivery penalties; client authorized settlement floor of $150k.", at: stampDaysAgo(7, 16, 0), authorId: "u9", matterId: "m3" },
];

const activities: Activity[] = [
  { id: "ac1", at: stampDaysAgo(0, 9, 5), actor: "Victoria Chen", text: "Called Kevin O'Rourke to confirm consultation", leadId: "l8" },
  { id: "ac2", at: stampDaysAgo(0, 8, 55), actor: "Lena Kowalski", text: "Received email from Marcus Delgado with case documents notice", leadId: "l1" },
  { id: "ac3", at: stampDaysAgo(0, 8, 0), actor: "System", text: "SMS consultation reminder sent to Angela Brooks", leadId: "l7" },
  { id: "ac4", at: stampDaysAgo(1, 16, 45), actor: "Lena Kowalski", text: "Sent post-consultation engagement package to Mariana Flores", leadId: "l9" },
  { id: "ac5", at: stampDaysAgo(1, 10, 0), actor: "Grace Okafor", text: "Marked consultation completed — recommended engagement", leadId: "l9" },
  { id: "ac6", at: stampDaysAgo(1, 9, 40), actor: "Lena Kowalski", text: "Uploaded signed retainer from Tanya Becker", leadId: "l11" },
  { id: "ac7", at: stampDaysAgo(2, 13, 0), actor: "Victoria Chen", text: "Sent retainer agreement to Robert Lindqvist", leadId: "l10" },
  { id: "ac8", at: stampDaysAgo(2, 11, 25), actor: "Daniel Reyes", text: "Uploaded Demand Letter — Draft v2", matterId: "m1", clientId: "c1" },
  { id: "ac9", at: stampDaysAgo(3, 13, 15), actor: "Daniel Reyes", text: "Phone call with Rosa Jimenez re: settlement counter", matterId: "m7", clientId: "c8" },
  { id: "ac10", at: stampDaysAgo(4, 10, 20), actor: "Grace Okafor", text: "Filed I-589 supplement with USCIS", matterId: "m2", clientId: "c2" },
  { id: "ac11", at: stampDaysAgo(5, 15, 30), actor: "Daniel Reyes", text: "Uploaded SaveMart settlement offer", matterId: "m7", clientId: "c8" },
  { id: "ac12", at: stampDaysAgo(6, 13, 20), actor: "Marcus Webb", text: "Logged interrogatories received from Apex counsel", matterId: "m3", clientId: "c3" },
];
// __PART5__
